{% set name = "lets-plot" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JetBrains/lets-plot/archive/v{{ version }}.tar.gz
  sha256: 07dbb8185d92524d10909b3cf026c4cdce91b8aa8da8b0ec6869e2b5c101332e

build:
  number: 0

requirements:
  build:
    - openjdk =11
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - pypng
    - palettable

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - lets_plot
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://lets-plot.org
  license: MIT
  license_file:
    - LICENSE
    - plot-base/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/base/stat/math3/NOTICE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
