{% set name = "lets-plot" %}
{% set version = "4.8.3.dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
#  url: https://github.com/JetBrains/lets-plot/archive/v{{ version }}.tar.gz
#  sha256: 39a19a20415c9f3a87d61bf04b14cc18109f78d3234f41ed9792b2f0ec7e94ae
  git_url: https://github.com/JetBrains/lets-plot.git
  git_rev: conda-build

build:
  skip: true  # [win]
  number: 0
  script_env:
   - PROJECT_VERSION=v{{ version }}
   - IMAGICK_LIB_PATH={{ PREFIX }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - openjdk =17
  host:
    - fonts-conda-forge
    - fontconfig
    - freetype
    - expat
    - imagemagick=7.1.1_46
    - zlib 
    - python
    - pip
    - setuptools
    - unzip  # [linux]
  run:
    - fontconfig
    - freetype
    - fonts-conda-forge
    - expat
    - pillow
    - pypng
    - palettable
    - imagemagick==7.1.1_46

test:
  imports:
    - lets_plot
  requires:
    - pip
  commands:
    - pip check
    - magick -list font

about:
  home: https://lets-plot.org
  summary: 'Lets-Plot is a multiplatform plotting library built on the principles of the Grammar of Graphics.'
  license: MIT
  license_file:
    - LICENSE
    - license-files/
    - plot-base/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/base/stat/math3/NOTICE
  dev_url: https://github.com/JetBrains/lets-plot
  doc_url: https://lets-plot.org/python/index.html#python-index-user-guide

extra:
  recipe-maintainers:
    - VDovidaytis-HORIS
